services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django-monolith:1.0.0
    container_name: django
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/www/static:/var/www/static
      - /var/www/media:/var/www/media
    depends_on:
      - db
    env_file:
      - ./backend/config/.env

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env.db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /var/www/static:/var/www/static
    depends_on:
      - django
volumes:
    postgres_data: