version: "3.7"

services:
  web:
      build: ./backend
      command: "python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./backend:/usr/src/app/
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file:
        - ./backend/config/.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

volumes:
  postgres_data:
