# Generated by Django 4.1.4 on 2024-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='riot_id',
            field=models.CharField(default='a', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
