# Generated by Django 4.1.4 on 2024-11-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchchampion_simplematch_matchchampion_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='position',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('JGL', 'Jungle'), ('MID', 'Middle'), ('BOT', 'Bottom'), ('SUP', 'Support')], max_length=64, null=True),
        ),
    ]
