# Generated by Django 4.1.4 on 2024-11-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_champion_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_earned', models.DecimalField(decimal_places=5, max_digits=15)),
                ('experience', models.DecimalField(decimal_places=5, max_digits=15)),
                ('kills', models.DecimalField(decimal_places=5, max_digits=15)),
                ('deaths', models.DecimalField(decimal_places=5, max_digits=15)),
                ('assists', models.DecimalField(decimal_places=5, max_digits=15)),
                ('time_ccing', models.DecimalField(decimal_places=5, max_digits=15)),
                ('total_cc_time', models.DecimalField(decimal_places=5, max_digits=15)),
                ('turret_takedowns', models.DecimalField(decimal_places=5, max_digits=15)),
                ('true_dmg_taken', models.DecimalField(decimal_places=5, max_digits=15)),
                ('magic_dmg_taken', models.DecimalField(decimal_places=5, max_digits=15)),
                ('physical_dmg_taken', models.DecimalField(decimal_places=5, max_digits=15)),
                ('self_dmg_mitigated', models.DecimalField(decimal_places=5, max_digits=15)),
                ('true_dmg_dealt', models.DecimalField(decimal_places=5, max_digits=15)),
                ('magic_dmg_dealt', models.DecimalField(decimal_places=5, max_digits=15)),
                ('physical_dmg_dealt', models.DecimalField(decimal_places=5, max_digits=15)),
                ('turrets_dmg_dealt', models.DecimalField(decimal_places=5, max_digits=15)),
                ('teammate_heals', models.DecimalField(decimal_places=5, max_digits=15)),
                ('teammate_shields', models.DecimalField(decimal_places=5, max_digits=15)),
                ('self_heal', models.DecimalField(decimal_places=5, max_digits=15)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.champion')),
            ],
        ),
    ]
