# Generated by Django 4.1.4 on 2024-11-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_championclass_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championclass',
            name='champion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='champ_class', to='matches.champion'),
        ),
    ]
