# Generated by Django 4.1.4 on 2024-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_championclass_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplematch',
            name='exp_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplematch',
            name='game_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplematch',
            name='gold_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplematch',
            name='kill_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplematch',
            name='won',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
