# Generated by Django 4.1.4 on 2025-01-22 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_simplematch_exp_difference_simplematch_game_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 0, 0)),
        ),
        migrations.CreateModel(
            name='ChampionCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counters', models.JSONField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.champion')),
            ],
        ),
    ]
