# Generated by Django 4.1.4 on 2025-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_player_last_update_championcounters'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='simplematch',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
    ]
