# Generated by Django 4.1.4 on 2025-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_simplematch_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('position', models.CharField(max_length=256)),
                ('allies', models.JSONField()),
                ('enemies', models.JSONField()),
                ('bans', models.JSONField()),
                ('predicitons', models.JSONField()),
            ],
        ),
    ]
